# 1. Create a null vector of size 10 but the fifth value which is 1.

In [2]:
import numpy as np

In [4]:
x = np.zeros(10)
x[4] = 1
print(x)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


# Create a vector with values ranging from 10 to 49.

In [5]:
print(np.arange(10,49))

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


# Create a 3x3 matrix with values ranging from 0 to 8

In [8]:
print(np.arange(0,9).reshape(3,3))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


# Find indices of non-zero elements from [1,2,0,0,4,0]

In [16]:
A = [1,2,0,0,4,0]
B = []

for i in range(len(A)):
    if A[i] != 0:
        B.append(i)
print(B)

[0, 1, 4]


# Create a 10x10 array with random values and find the minimum and maximum values.

In [22]:
x = np.random.random((10,10))
xmin, xmax = x.min(), x.max()
# print(x)
print("min : ",x.min())
print("max : ",x.max())

min :  0.019233190474456374
max :  0.9871769489220894


# Create a random vector of size 30 and find the mean value.

In [29]:
x = np.random.random((30))
print("Mean is : ",x.mean())

Mean is :  0.5039453559000867
